[IV 23-24] Objetivo 0
Christianlr/MIBarberSchedule pull request #1
Opened 2023-09-19 14:50 UTC by Christianlr

* [x] ¿Se trata de un problema real del que se tenga conocimiento personal?
Si, tengo un amigo muy cercano y me lo ha comentado varias veces. Se que se suele hacer en este tipo de tareas y el tiempo que se necesita para cada una de ellas.
* [x] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
Si, el y sus compañeros necesitan comprobar siempre que deseen dicha planificación de trabajos.
* [x] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
Si, ya que se procesa una planificación de dichas tareas en los mejores momentos posibles para cada uno de los barberos trabajando en el local, teniendo en cuenta sus ocupaciones.
* [x] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
`README`?
Si, todo está presente.
* [x] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas
a requerir que el usuario los introduzca?
Si, la lista de tareas es conocida. Lo único necesario que los barberos deben de introducir es el tiempo libre que tienen.
* [ ] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún
todo?

2023-09-20 06:15 UTC, JJ commented
Debes usar el cliente de git, no añadir los ficheros subiéndolos. Usar git es fundamental para cualquier trabajo profesional de informática.

2023-09-20 06:21 UTC, JJ commented
> * [x]  ¿Se trata de un problema real del que se tenga conocimiento personal?
>       Si, ya que soy uno de esos encargados y se que se necesita saber.
> 
>     * [x]  ¿Se trata de un problema que para solucionar requiera el despliegue
>       de una aplicación en la nube?
>       Si, para que todos podamos visualizar los datos mejor además de ver sugerencias y predicciones.
> 
>     * [x]  ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
>       solucionarse sólo almacenando y buscando?
>       Si, se necesitan cálculos para determinar el clima de aquellos días próximos que nos gustaría saber.

¿Son cálculos que vas a hacer tú *dentro de esta asignatura*? ¿A partir de qué? En [el guión del objetivo](http://jj.github.io/IV/documentos/proyecto/0.Repositorio) habla de qué es la *lógica de negocio*, y dice:

> Propio quiere decir que toda la lógica de negocio tendrá que ser programada por el estudiante, principalmente en el [objetivo 4](http://jj.github.io/IV/documentos/proyecto/4.Tests), y de ahí en adelante. Es decir, en este punto tienes que tener al menos una idea vaga de cómo resolver el problema mediante código con tus propios medios.

Por otro lado, el mismo guión menciona repetidamente la metodología de *design thinking* para entender y describir correctamente el problema que se va a resolver. Se hizo un juego en clase para aplicarla, pero si no puedes o no quieres hacerlo, en todo caso tendrás que aplicar esa metodología para tratar de describir bien un problema. En ingeniería, usar las mejores prácticas para llevar a cabo un paso de un proyecto (porque de eso se trata) es esencial para poder emprender un proyecto correctamente.

2023-09-20 16:58 UTC, JJ requested changes
Si establecemos que ya conoces a gente que hace rutinas deportivas habla con ellos hasta que te describan qué problemas hay y puedas encontrar alguno que pueda aplicarse en la asignatura; la fase de empatía de *design thinking* consiste realmente en eso, en poder identificar problemas entre lo que te dice la gente.

En general, en este objetivo lo que se busca es que aprendáis a usar una metodología para definir los problemas que se puedan resolver mediante una aplicación. Sin usar esa metodología puede salir, claro que sí, pero en general, como ha sucedido hasta ahora, presentarán una serie de obstáculos para poder usarse realmente.

De la misma forma, te rogaría que cuando desees evaluación la pidas explícitamente.

2023-09-21 07:57 UTC, Christianlr commented
Listo para revisión.

2023-09-21 10:16 UTC, JJ requested changes
Recuerda también que tienes que tener conocimiento personal del tema simplemente para poder encontrar una solución realista.

2023-09-21 10:16 UTC, JJ commented on README.md
> +Soy barbero y a lo largo de la semana nos resulta complicado a mi y a mis compañeros llevar a cabo las tareas básicas para el mantenimiento del local y los materiales, como pueden ser limpieza de maq
OK, más o menos entiendo el contexto del problema, pero recuerda que tienes que identificar un cliente, qué es lo que hace ese cliente, y qué no puede hacer. ¿El cliente organiza las tareas diarias? ¿En base a qué datos?

2023-09-21 11:02 UTC, Christianlr commented on README.md
> +Soy barbero y a lo largo de la semana nos resulta complicado a mi y a mis compañeros llevar a cabo las tareas básicas para el mantenimiento del local y los materiales, como pueden ser limpieza de maq
Mi cliente en todo momento va a ser el barbero/los barberos que trabajan en ese local. Lo que pueden hacer es planificar, mediante un proceso automático, las tareas que cada uno de ellos va a hacer a lo largo de la semana en función del tiempo libre que ellos tengan durante esta. Esto quiere decir, que solo se dispone como dato de entrada ese tiempo libre en un día o días determinados de la semana que hace posible esa planificación.

2023-09-21 11:04 UTC, Christianlr commented on README.md
> +Soy barbero y a lo largo de la semana nos resulta complicado a mi y a mis compañeros llevar a cabo las tareas básicas para el mantenimiento del local y los materiales, como pueden ser limpieza de maq
Con respecto al conocimiento personal, muchas veces he ido a verlos y he pasado tiempo con ellos en su ámbito laboral. Por lo que tengo constancia de aquellas actividades que suelen realizar a lo largo del día.

2023-09-21 11:10 UTC, Christianlr commented on README.md
> +Soy barbero y a lo largo de la semana nos resulta complicado a mi y a mis compañeros llevar a cabo las tareas básicas para el mantenimiento del local y los materiales, como pueden ser limpieza de maq
@JJ Listo para revisar.

2023-09-21 11:34 UTC, JJ commented on README.md
> +Soy barbero y a lo largo de la semana nos resulta complicado a mi y a mis compañeros llevar a cabo las tareas básicas para el mantenimiento del local y los materiales, como pueden ser limpieza de maq
Estará listo cuando lo modifiques. Todo lo que tengas que decir sobre el problema lo tienes que decir en el PR.

2023-09-21 12:02 UTC, Christianlr commented
Ya he actualizado y aclarado un poco más el README.md @JJ Listo para revisión.

2023-09-21 12:04 UTC, JJ approved these changes
:+1:

2023-09-21 12:06 UTC, merged