[IV-23-24] Objetivo-3
Christianlr/MIBarberSchedule pull request #24
Opened 2023-11-09 09:26 UTC by Christianlr

* [ ] ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [ ] ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [ ] ¿Ese issue está asignado a un milestone?
* [ ] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [ ] ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [ ] ¿El PR, que también es un issue, está asignado al mismo milestone?
* [ ] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes y sólo eso?
* [ ] ¿Se ha comprobado que las instrucciones incluidas en el `README.md` son
completas y correctas?

2023-11-10 08:23 UTC, pluque01 approved these changes
En general está muy bien. Creo que has documentado correctamente todas las opciones indicando en qué se diferencian. Salvo las cosillas que te comento te doy el visto bueno :))

2023-11-10 08:23 UTC, pluque01 commented on docs/gestor_dependencias.md
> +Tras el estudio realizado de las principales alternativas que se presentan como gestores de dependencias, elijo PNPM. Basicamente, me parece una opción más que correcta para el desarrollo de este pro
Muy buena conclusión!

2023-11-10 08:23 UTC, pluque01 commented on docs/gestor_tareas.md
> +-   Que se presente facilidad en el mantenimiento y ejecución de tareas.
Igual este criterio es un poco ambiguo

2023-11-10 08:23 UTC, pluque01 commented on docs/gestor_tareas.md
> +## Make y Just
Puedes poner un enlace a la web de los que mencionas, al profesor le gusta eso :))

2023-11-10 08:23 UTC, pluque01 commented on docs/gestor_tareas.md
> +Una de las grandes ventajas que tenemos al usar NPM Scripts es la automatización de tareas en el mismo fichero package.json. En relativamente sencillo de hacer y no seria necesario instalar ninguna h
typo en `seria`

2023-11-10 08:23 UTC, pluque01 commented on docs/gestor_tareas.md
> +De Grunt nos con que se configura mediante un fichero en JavaScript. Es más lento que Gulp por su enfoque E/S de archivos en disco y ejecuciones secuenciales.
Falta algo después de **nos**, ¿no?

2023-11-10 08:23 UTC, pluque01 commented on docs/gestor_tareas.md
> +Por otra parte, Gulp presenta un código más legible y conciso a través de tuberias. Es flexible y carga en memoria, por lo que es más rápido. Otro punto a destacar es la ejecución de tareas en parale
typo en `tuberias`

2023-11-10 08:23 UTC, pluque01 commented on docs/runtime.md
> +- Estabilidad o velocidad? : Nuestro proyecto no se basa en dar datos rápidos que son imprescindibles al momento o algo parecido. Por lo que pensar en una estabilidad en la que simplemente funcione c
Me parece muy correcto que no tomes la velocidad como algo necesario, y te decantes más bien por la estabilidad. Sin embargo la última frase yo la pondría en otro punto, no en estabilidad.

2023-11-10 08:23 UTC, pluque01 commented on docs/runtime.md
> +Los casos de uso en los que node tendría un papel ideal son, entre otros, en aplicaciones de una sola página (SPA) y vinculadas a E/S. Este proyecto, en cierta parte, tiene vinculos con ambos escenar
typo en `vinculos`

2023-11-10 08:23 UTC, pluque01 commented on docs/runtime.md
> +A diferencia de node, no se necesita hacer gran cosa para poder usar TypeScript en el, ya que es compatible de primeras. Lo único es que no hay mucha documentación y aunque hay actividad en foros y d
typo en `el`

2023-11-10 08:23 UTC, pluque01 commented on docs/runtime.md
> +Tras estudiar las distintas características de los principales runtimes que hay, elijo node.js. Puede parecer el menos seguro pero actualmente en su v21.0 ofrece posibilidades similares en cuanto a s
typo en `increible`

2023-11-10 09:25 UTC, PabloBarTo approved these changes
En general me parece que está todo correcto y por añadir algo a la review de @pluque01 cambiaría lo que te he dicho en el comentario que te he dejado. :smile:

2023-11-10 09:25 UTC, PabloBarTo commented on docs/gestor_tareas.md
> +-   Que se presente facilidad en el mantenimiento y ejecución de tareas.
Yo modificaría este criterio ya que facilidad en sí no es algo que se pueda medir con un número o porcentaje para determinar que es mejor que otro gestor de tareas. Además en el documento de errores frecuentes aparece que criterios como "facilidad de uso" no son del todo válidos.

2023-11-14 18:15 UTC, Christianlr commented on docs/gestor_dependencias.md
> +Tras el estudio realizado de las principales alternativas que se presentan como gestores de dependencias, elijo PNPM. Basicamente, me parece una opción más que correcta para el desarrollo de este pro
Gracias! :+1:

2023-11-14 18:16 UTC, Christianlr commented on docs/gestor_tareas.md
> +-   Que se presente facilidad en el mantenimiento y ejecución de tareas.
Tienes razón, lo he cambiado basándome en otro criterio más acorde.

2023-11-14 18:17 UTC, Christianlr commented on docs/gestor_tareas.md
> +## Make y Just
Acabo de poner un enlace para Just ya que puede ser aquel del que menos constancia se tenga! Si consideras que debo agregar un enlace para cada uno de ellos, lo hago sin problema!

2023-11-14 18:18 UTC, Christianlr commented on docs/gestor_tareas.md
> +Una de las grandes ventajas que tenemos al usar NPM Scripts es la automatización de tareas en el mismo fichero package.json. En relativamente sencillo de hacer y no seria necesario instalar ninguna h
Arreglado! :tada:

2023-11-14 18:18 UTC, Christianlr commented on docs/gestor_tareas.md
> +De Grunt nos con que se configura mediante un fichero en JavaScript. Es más lento que Gulp por su enfoque E/S de archivos en disco y ejecuciones secuenciales.
Me faltó una palabra! Buena vista! :wink:

2023-11-14 18:18 UTC, Christianlr commented on docs/gestor_tareas.md
> +Por otra parte, Gulp presenta un código más legible y conciso a través de tuberias. Es flexible y carga en memoria, por lo que es más rápido. Otro punto a destacar es la ejecución de tareas en parale
Arreglado! :tada:

2023-11-14 18:18 UTC, Christianlr commented on docs/runtime.md
> +Los casos de uso en los que node tendría un papel ideal son, entre otros, en aplicaciones de una sola página (SPA) y vinculadas a E/S. Este proyecto, en cierta parte, tiene vinculos con ambos escenar
Arreglado! :tada:

2023-11-14 18:19 UTC, Christianlr commented on docs/runtime.md
> +Tras estudiar las distintas características de los principales runtimes que hay, elijo node.js. Puede parecer el menos seguro pero actualmente en su v21.0 ofrece posibilidades similares en cuanto a s
Arreglado! :tada:

2023-11-14 18:19 UTC, Christianlr commented on docs/runtime.md
> +A diferencia de node, no se necesita hacer gran cosa para poder usar TypeScript en el, ya que es compatible de primeras. Lo único es que no hay mucha documentación y aunque hay actividad en foros y d
Arreglado! :tada:

2023-11-14 18:20 UTC, Christianlr commented on docs/gestor_tareas.md
> +-   Que se presente facilidad en el mantenimiento y ejecución de tareas.
Tal y como le he comentado a @pluque01, ambos teneis razón. Se me pasó por completo. Lo acabo de arreglar! Ya me dices que te parece! :wink:

2023-11-14 19:35 UTC, PabloBarTo approved these changes
Yo lo veo bastante bien. Lo de añadir imágenes para apoyar la explicación de un criterio creo que es una gran idea ya que ayuda a darle como más credibilidad a ese criterio. Buen trabajo!!👍.

2023-11-15 19:00 UTC, Christianlr commented
@JJ Listo para revisión!

2023-11-17 08:21 UTC, JJ requested changes
A casi todos los efectos prácticos, el objetivo está superado. Sin embargo, te agradecería que pusieras un poco de más precisión describiendo las herramientas consideradas, y la elección que has hecho. Gracias también a @pluque01 y @PabloBarTo por la interacción

2023-11-17 08:21 UTC, JJ commented on README.md
> +```ruby
¿ruby?
Sería shell...

2023-11-17 08:21 UTC, JJ commented on docs/gestor_dependencias.md
> +## NPM
No son siglas, o no se usan como tales...

2023-11-17 08:21 UTC, JJ commented on docs/gestor_dependencias.md
> +-   CLI puede llegar a ser complejo.
¿Fuente para esto? El cli es el mismo que para `npm`, al menos en las tareas comunes.

2023-11-17 08:21 UTC, JJ commented on docs/gestor_tareas.md
> +Podria decantarme por cualquiera de ambas, de verdad. Pero si se analiza un poco más la situación podemos llegar a la conclusión de que realmente ya disponemos de la solución. Voy a usar NPM Scripts,
¿Estás usando npm scripts para decir package.json scripts? En todo caso, estarías usando `pnpm` scripts, ¿no?

2023-11-17 08:21 UTC, JJ commented on docs/runtime.md
> +Bun se trata de un all-in-one toolkit super rápido siendo este de los 3 destacados el más rápido. Solventa principalmente la complejidad que ha tenido node a lo largo del tiempo de desarrollo. Al igu
Considera si has puesto aquí un poco de más texto del necesario para entender tu elección.

2023-11-17 12:21 UTC, Christianlr commented on README.md
> +```ruby
Arreglado! :tada:

2023-11-17 12:22 UTC, Christianlr commented on docs/gestor_dependencias.md
> +## NPM
Entiendo que no es solo usar las siglas, si no entender de que tratan. Creo que lo he arreglado!

2023-11-17 12:23 UTC, Christianlr commented on docs/gestor_dependencias.md
> +-   CLI puede llegar a ser complejo.
Tal y como se menciona, cuando se hace un estudio posterior a cuando se escribió esa sentencia, lo primero es que no es correcto del todo ni hablar de complejidad ni de facilidad en cuanto a una herramienta. Por lo tanto, he procedido a eliminar esa declaración :-1:

2023-11-17 12:25 UTC, Christianlr commented on docs/gestor_tareas.md
> +Podria decantarme por cualquiera de ambas, de verdad. Pero si se analiza un poco más la situación podemos llegar a la conclusión de que realmente ya disponemos de la solución. Voy a usar NPM Scripts,
Toda la razón. No tiene sentido hablar de `NPM Scrips` cuando se origina un `package.json` partiendo de PNPM. Arreglado! :tada:

2023-11-17 12:26 UTC, Christianlr commented on docs/runtime.md
> +Bun se trata de un all-in-one toolkit super rápido siendo este de los 3 destacados el más rápido. Solventa principalmente la complejidad que ha tenido node a lo largo del tiempo de desarrollo. Al igu
Tal y como he mencionado más arriba, el tema de la complejidad considero que no es correcto del todo y he procedido a eliminarlo. Si hay alguna otra sentencia que verdaderamente no sea relevante, lo modifico sin problema!

2023-11-17 12:27 UTC, Christianlr commented
@JJ Te agradezco que me hayas indicado aquellos apartados que pueden ser mejorados. Creo que las modificaciones que he realizado se acercan más a lo que se busca. Listo para revisión! :+1:

2023-11-17 12:32 UTC, JJ approved these changes
👍

2023-11-17 12:32 UTC, JJ commented on tsconfig.json
> +    // "lib": [],                                        /* Specify a set of bundled library declaration files that describe the target runtime environment. */
Borrad el boilerplate, porfa.

2023-11-17 12:32 UTC, JJ commented on docs/runtime.md
> +Tras estudiar las distintas características de los principales runtimes que hay, elijo node.js. Puede parecer el menos seguro pero actualmente en su v21.0 ofrece posibilidades similares en cuanto a s
la versión 21 está en desarrollo, pero puedes usarla si te apetece y si tiene lo que necesitas

2023-11-17 12:32 UTC, JJ commented on docs/gestor_tareas.md
> +Son bastante parecidas entre sí. Realmente son populares en la comunidad y dos de las más usadas. Hay mucha gente que prefiere Grunt y otros que prefieren Gulp. Pero no es un factor a tener en cuenta
gulp no. No me mentéis más gulp, que está obsoleto.

2023-11-17 12:43 UTC, merged