[IV-23-24]Objetivo 5
Christianlr/MIBarberSchedule pull request #48
Opened 2023-12-08 19:42 UTC by Christianlr

* [ ] ¿Se han establecido criterios previos de elección de la imagen base, así
como los criterios de búsqueda que han conducido a las imágenes que se están
considerando?
* [ ] ¿Se ha tenido en cuenta que la imagen es para testear, y que por tanto
tiene una función específica, tal como testear cómo va nuestra aplicación en la
última versión publicada del lenguage?
* [ ] ¿Se ha tenido en cuenta que la versión de la imagen base sea la última?
* [ ] ¿Se han tenido en cuenta criterios reales para la elección, y no criterios
irrelevantes como cuanto tiempo se tarda en construirla? (Se va a construir una
vez, se va a usar cientos o miles de veces)
* [ ] ¿Se han seguido las buenas prácticas en las órdenes que construyen
   la imagen? ¿Especialmente las relativas a usuarios no privilegiados y demás?
* [ ] ¿La imagen incluye sólo y exclusivamente la infraestructura
   necesaria para pasar los tests? Por ejemplo, si se ha elegido la imagen
   "oficial" (lo que hay que hacer sólo en casos muy justificados) ¿se ha
   comprobado que lo que se instale sea sólo y exclusivamente lo necesario para
   nuestro proyecto?
* [ ] ¿Se han documentado y enlazado los commits a las imágenes que se
   han testeado?
* [ ] ¿Está establecido correctamente como `WORKDIR` el que se va a usar en los
   tests que se van a lanzar?
* [ ] ¿Se usa algún directorio adecuado para copiar contenidos del repositorio
en vez del directorio de trabajo?
* [ ] ¿Se han establecido claramente los criterios de búsqueda y de aceptación de
   la imagen base?
* [ ] ¿Tienes claro cuales son las condiciones en las que tiene que actualizarse
la imagen en DockerHub y has configurado el workflow de acuerdo con ello? En
particular, ¿sabes qué condiciones tienen que darse para que se actualice y qué
condiciones *no* deben darse?
* [ ] Si se usan GitHub actions para su publicación, ¿se han considerado
cuidadosamene los criterios (ramas, paths) para que se lancen?
* [ ] ¿Se ha comprobado que el ENTRYPOINT del contenedor no escriba nada en el
directorio que monta, ya que no tiene derecho de escritura?
* [ ] ¿Se ha abierto un shell en el contenedor una vez construida la imagen y
comprobado que los ficheros que se necesitan están todos incluidos, y que no hay
ficheros que no se necesiten?

2023-12-10 09:15 UTC, manuelvico0102 requested changes
Buenas, voy a ser tu revisor. En general lo veo bastante bien. Te faltaría arreglar lo del actions y creo que ya estaría todo. Porque el dockerfile imagino que le das todos los permisos para que te funcionase aunque no sea una buena práctica.

2023-12-10 09:15 UTC, manuelvico0102 commented on .github/workflows/contenedor.yml
> +      - name: Login to Docker Hub
He visto que tienes un error al realizar el login, seguramente no tengas configurado los secretos o en dockerhub no le hayas dado los permisos necesarios.

2023-12-10 09:15 UTC, manuelvico0102 commented on .github/workflows/contenedor.yml
> +          tags: enaraque/bus_stadistics:latest
Deberías cambiar esto, ya que este no es tu imagen

2023-12-10 11:15 UTC, Christianlr commented on .github/workflows/contenedor.yml
> +      - name: Login to Docker Hub
Arreglado! :tada:

2023-12-10 11:18 UTC, Christianlr commented on .github/workflows/contenedor.yml
> +          tags: enaraque/bus_stadistics:latest
Ha sido un total despiste. Ya lo he cambiado. Cuando usé mi workflow no entendía porque no terminada de aceptar el PR aun teniendo mi imagen puesta y mis credenciales de dockerhub configuradas. Hablando con el me dijo que intentase cambiar los parámetros de la última parte al suyo y no modifiqué esto sin querer. Ahora si funciona, gracias por la observación! :sunglasses:

2023-12-10 11:20 UTC, Christianlr commented
Buenas @manuelvico0102!! Muchas gracias por la revisión. He modificado y arreglado los errores que has mencionado. Uno de ellos un poco descuido, la verdad. Cuando puedas me comentas si esos permisos que he puesto en el Dockerfile son correctos o hay que hacer alguna otra modificación :wink:

2023-12-10 11:25 UTC, manuelvico0102 approved these changes
Yo ya lo veo todo correcto. 👍 👌

2023-12-12 11:25 UTC, Christianlr commented
@JJ Espero alguna revisión más o se puede revisar ya?

2023-12-12 16:12 UTC, JJ commented
Como tú veas. Ya han pasado 4 días de la entrega, si quieres revisión, no tienes más que pedirlo; si quieres que alguno de los que se te han asignado revise, pídeselo. Por ejemplo a @enaraque no le vendría mal alguna revisión más.

2023-12-12 16:28 UTC, Christianlr commented
@Enaraque Listo para revisión :cold_face:

2023-12-14 19:17 UTC, JJ requested changes
El problema principal es la elección de la imagen base. Por favor, considera otras opciones con las que creo que aprenderás más y podrás de esa forma alcanzar los objetivos, que son objetivos de aprendizaje.

2023-12-14 19:17 UTC, JJ commented on Dockerfile
> +FROM node:bookworm-slim AS base
`as base` se usa sólo cuando vayas a trabajar con una construcción de dos fases, que parece que no es el caso.
En todo caso, a estas alturas casi todas las combinaciones de imagen base y de slim o no se han usado ya. Creo que cuando empecé a explicar a la segunda o tercera generación os dije que usárais directamente imágenes base con el sistema operativo sólo y a partir de ahí instalárais lo qeu necesitárais. No es demasiado complicado instalar node (no debería serlo, por otro lado) ni, una vez hecho, instalar pnpm (hay una página para instalar `pnpm` en cualquier sistema operativo conocido. Creo que aprenderéis bastante más si lo hacéis así en vez de usar las máquinas base que tienen ya de todo.

2023-12-14 19:17 UTC, JJ commented on Dockerfile
> +RUN npm install -g pnpm@latest
Incluso aunque decidas usar la imagen base de node, la página de `pnpm` indica otras maneras de hacer esta instalación que no necesitan `npm`. El problema no es que usen o no npm, sino que npm va a instalar una serie de ficheros que posiblemente no necesites, y resulte en una imagen con un tamaño excesivo.

2023-12-14 19:17 UTC, JJ commented on docs/eleccion_imagen_base.md
> +- Otras posibilidades consideradas: **Debian**, **Fedora** o incluso **CentOS**. Podríamos trabajar con node sin problemas. Pero antes de eso, deberíamos de obtener las herramientas necesarias. Enton
En clase os expliqué que había tres tipos de imágenes, y eso si nos limitamos a imágenes que ya tengan node. Aquí estás considerando sólo uno. Si sólo consideras uno, el margen de elección (y por tanto de aprendizaje) no es muy amplio. Por favor, considera trabajar solamente con la imagen base con el sistema operativo, pero si al final decides no hacerlo, tendrás en todo caso que contemplar más opciones entre las imágenes base elegidas.

2023-12-15 16:50 UTC, Christianlr commented on Dockerfile
> +FROM node:bookworm-slim AS base
Resuelto en https://github.com/Christianlr/MIBarberSchedule/pull/48/commits/2bcd61cc0007a64007ab9cd1bd5d84d101d00246 :tada: !

2023-12-15 16:50 UTC, Christianlr commented on Dockerfile
> +RUN npm install -g pnpm@latest
Resuelto en https://github.com/Christianlr/MIBarberSchedule/commit/2bcd61cc0007a64007ab9cd1bd5d84d101d00246 🎉 !

2023-12-15 16:50 UTC, Christianlr commented on docs/eleccion_imagen_base.md
> +- Otras posibilidades consideradas: **Debian**, **Fedora** o incluso **CentOS**. Podríamos trabajar con node sin problemas. Pero antes de eso, deberíamos de obtener las herramientas necesarias. Enton
Resuelto en https://github.com/Christianlr/MIBarberSchedule/pull/48/commits/66d420f0ac45c53e2ed9c524d011e41133958a6d :tada: !

2023-12-15 16:52 UTC, Christianlr commented
@JJ lo primero muchas gracias por comentarme los errores y por lo visto en clase. Le acabo de subir los cambios aunque he visto que ya estaba aceptado. Nada, si sigue viendo algo incompleto me lo dice y lo arreglo en un momento!! :+1:

2023-12-15 18:29 UTC, JJ commented
La verdad es que pensaba que lo había aprobado, pero parece que no lo había hecho. Lo miro rápidamente. El error que hay parece transitorio, prueba a ejecutarlo de nuevo a ver.

2023-12-15 18:32 UTC, JJ approved these changes
:+1: No voy a cambiar la revisión, lo hecho hecho está, pero por favor trata de hacer lo que te comento con órdenes sucesivas. También debería mejorar algo el tamaño, sobre todo las `RUN`

2023-12-15 18:32 UTC, JJ commented on Dockerfile
> +ENV PNPM_HOME="/pnpm"
¿No crees que es mejor juntar todas las sentencias iguales seguidas en una sola? Por ejemplo las `RUN` y las `ENV`

2023-12-20 18:35 UTC, Christianlr commented on Dockerfile
> +ENV PNPM_HOME="/pnpm"
Arreglado en https://github.com/Christianlr/MIBarberSchedule/pull/48/commits/df219c025a91c10b6d036dfb70e8e0072ea583fb :tada:

2023-12-20 18:36 UTC, merged