[IV-23-24] Objetivo 2
Christianlr/MIBarberSchedule pull request #7
Opened 2023-10-06 11:20 UTC by javigp2002

Debatido lenguaje de programación #6, closes #6

2023-10-12 09:45 UTC, javigp2002 commented
@Christianlr Buenas, creo que he terminado de hacer todos los ficheros. Echale un vistazo a ver si estamos cumpliendo con los requisitos, no obstante, he hecho un cambio que te comento en el #13, miralo si puedes :construction: . Por cierto, me parece que tienes que rellenar esto según pone en [Objetivo 2](http://jj.github.io/IV/documentos/proyecto/2.Modelo):

* [ ] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [ ] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [ ] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [ ] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [ ] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?
* [ ] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [ ] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?

2023-10-12 10:01 UTC, Christianlr commented
@javigp2002 Ya he revisado lo que comentaste en #13 y además ya he rellenado la lista de comprobaciones que me correspondía :smile:

2023-10-17 07:53 UTC, Christianlr approved these changes
:+1:

2023-10-17 07:57 UTC, Christianlr commented
@JJ Listo para revisión

2023-10-17 11:18 UTC, JJ requested changes
Habéis sido de los primeros en proponer para revisión, y os felicito; desgraciadamente, ser pioneros tiene también sus problemas y es que hay que aprender de los propios errores en vez de aprender de los de otros. Ya os he señalado en cada lugar los principales problemas del código, pero lo principal es que tenéis que ser muy cuidadosos con los issues que creáis. Si no planteáis los problemas claramente, es muy complicado que lo resolváis con código que sea válido más adelante en el desarrollo del proyecto.
Al final, lo principal es que @Christianlr pueda usar esto en el objetivo 4; a veces es complicado simplemente mirando al código saber si va a servir o no, pero en tal caso lo que hay que hacer es una implementación de prueba de ese objetivo 4, al menos de los aspectos más básicos, a ver qué habría que hacer. Si hay que rehacer gran parte de los datos, o simplemente no está claro el modelo del problema a partir de los issues y las estructuras de datos corres pondientes, lo razonable es solicitar aclaraciones o que considere otras alternativas.

2023-10-17 11:18 UTC, JJ commented on iv.yaml
> +entidad: src/peaky_barber.ts
Esto ya no existe. En los siguiente PRs le dará error a @Christianlr

2023-10-17 11:18 UTC, JJ commented on src/agenda.ts
> +    inicio: Date,
No tengo muy claro qué issue de los cuatro de este commit https://github.com/javigp2002/MIBarberSchedule/commit/93edf1efc1a38f848fc693eba7f80b811109179f quieres manejar, por eso es muy complicado saber si esto sirve o no. Pero me da la impresión de que si las tareas comienzan y terminan en el mismo día, ¿no has considerado la posibilidad de almacenar día y hora aparte? Es más, ¿cómo se maneja este dato? ¿Se usa la duración? Si es así, ¿no será mejor almacenar hora de comienzo y duración?

2023-10-17 11:18 UTC, JJ commented on src/tarea.ts
> +    private _id: number;
los objetos valor se caracterizan por no tener un ID.

2023-10-17 11:18 UTC, JJ commented on src/tarea.ts
> +    private _fechaCreacion: Date;
Si, como dices en #13, las tareas tienen prioridad (no es que plantees el problema, pero has dicho que vas a implementarlo con una priority queue), ¿dónde tienes eso en cuenta aquí o en la agenda?

2023-10-17 11:18 UTC, JJ commented on src/trabajador.ts
> +        this._dni = dni;
¿Necesitas el DNI en un producto mínimamente viable?

2023-10-19 11:51 UTC, javigp2002 commented
@Christianlr Ya he hecho los cambios que he visto oportunos siguiendo los issues establecidos :building_construction:. Echale un vistazo cuando puedas, debería haberse adecuado a todo lo que hemos hablado esta mañana :monocle_face:.

2023-10-20 09:23 UTC, Christianlr approved these changes
@javigp2002 tras los problemas que aclaramos en clase, creo que la estructura y los conceptos se entienden mejor. Las clases las veo correctas y claras. Por otro lado, los issues ahora si tienen mucha mejor apariencia y contenido acorde a lo que son. Pienso que está todo bastante bien  😎👏

2023-10-20 11:11 UTC, Christianlr commented
@JJ Listo para revisión. Con respecto a lo que mencionabas sobre la cola de prioridad en #13 que no se reflejaba en el código, al final no se trabajará con ella, ya que `TypeScript` no cuenta con esta implementación.

2023-10-20 11:52 UTC, JJ commented
> @JJ Listo para revisión. Con respecto a lo que mencionabas sobre la cola de prioridad en #13 que no se reflejaba en el código, al final no se trabajará con ella, ya que `TypeScript` no cuenta con esta implementación.

Porfa, no os olvidéis de seguir la lista de comprobación.

2023-10-20 12:03 UTC, JJ requested changes
Por favor, revisad todos los comentarios y cambiad el código correspondiente. En este caso, mirad algún comentario adicional que os he hecho.

2023-10-20 12:03 UTC, JJ commented on src/agenda.ts
> +        this._tiempoLibreTrabajadores = [];
Si está declarado como Array creo que no puedes inicializarlo así.

2023-10-20 12:03 UTC, JJ commented on src/tarea.ts
> +    private _fechaCreacion: Date;
Igual, debes intentar mirar todos los comentarios y reaccionar.

2023-10-20 12:28 UTC, javigp2002 reviewed
@JJ Ya he revisado todos comentarios :building_construction:.

2023-10-20 12:28 UTC, javigp2002 commented on src/agenda.ts
> +    inicio: Date,
Efectivamente, estaba ya resuelto en un commit anterior, c2d448eaace7730e3fd1bcbba84b78788eeb8988.

2023-10-20 12:28 UTC, javigp2002 commented on src/tarea.ts
> +    private _fechaCreacion: Date;
Hecho :+1:.

2023-10-20 12:28 UTC, javigp2002 commented on src/agenda.ts
> +        this._tiempoLibreTrabajadores = [];
Efectivamente, no se hacía así y he eliminado el constructor por que lo hemos considerado innecesario. Resuelto en 5484ac4fe8db7618ac65a4cfea19ed737977e7ea.

2023-10-20 12:28 UTC, javigp2002 commented on src/agenda.ts
> +    duracion: number
Aunque ya estaba puesto en uno de los issues es mejor dejarlo determiando para futuras implementaciones. Resuelto e1c40dcae8475dee5f437ef9b46de238e7cb51d8. :+1: .

2023-10-20 15:40 UTC, JJ requested changes
Está muy cerca, salvo que debes tratar de resolver los comentarios correctamente, no sólo comentar, e incluir claramente en el modelo cómo se cuenta el tiempo. En cuanto a #15 si no lo vas a hacer finalmente no tienes por qué cerrarlo, simplemente dejarlo abierto, quizás con una etiqueta de `wontfix`.

2023-10-20 15:40 UTC, JJ commented on src/agenda.ts
> +    inicio: Date,
Puedes cerrarlo con "resolver comentario"

2023-10-20 15:40 UTC, JJ commented on src/tarea.ts
> +    private _fechaCreacion: Date;
... e igual, debes resolver el comentario.

2023-10-20 15:40 UTC, JJ commented on src/tarea.ts
> +    private _tiempoEstimado: number;
Igual que antes, deberías intentar especificar a qué se refiere el número o usar un tipo más preciso para expresarlo.

2023-10-20 16:44 UTC, javigp2002 commented
@Christianlr He corregido los errores comentados y me gustaría que los aprobases de nuevo 💯. Además, he creado #18 sobre el tiempo del que hemos estado comentando, añádele el M0 por favor. Asimismo, como ha comentado JJ en el #15 al no tener que hacerlo por la conclusión a la que llegamos, ponle una etiqueta de `wontfix`. ¡Muchas gracias por todo! 🥇

2023-10-21 11:24 UTC, Christianlr approved these changes
@javigp2002 Ya he añadido todo lo que has comentado. Por otra parte, se tiene un concepto más claro de cómo se almacena el tiempo. Gracias por los cambios! :sunglasses:  :100:

2023-10-21 11:26 UTC, Christianlr commented
@JJ Listo para revisión 🧐

2023-10-23 08:23 UTC, JJ approved these changes
👍

2023-10-23 08:23 UTC, JJ commented on src/tarea.ts
> +enum Prioridad{
¿Esto no se exporta?

2023-10-27 11:58 UTC, merged